apiVersion: v1
kind: Service
metadata:
  name: ctf-config-service-{{ .Values.color }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: ctf-config-service
    color: {{ .Values.color }}   # 🎯 BLUE / GREEN SWITCH
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
